---
title: "Lab 06 - Ugly charts and Simpson's paradox"
author: "Rachel Good"
date: "`r Sys.Date()`"
output: github_document
---

### Load packages and data

```{r load-packages, message = FALSE}
library(tidyverse) 
library(dsbox)
library(mosaicData) 

staff <- read_csv("data/instructional-staff.csv")
```

### Exercise 1

```{r exercise1}
staff_long <- staff %>%
  pivot_longer(cols = -faculty_type, names_to = "year") %>%
  mutate(value = as.numeric(value))

staff_long %>%
  ggplot(aes(x = year, y = value, group = faculty_type, color = faculty_type)) +
  geom_line() +
  labs(title = "Number of Faculty by Type", x = "Year", y = "Number of Faculty Members", color = "Type of Faculty")
```

### Exercise 2

You could potentially change the colors to emphasize the part-time faculty line (maybe make that line red and the others shades of blue). I also wonder if there is a way to simply make the part-time faculty line bolder/thicker than the other lines.

### Exercise 3

```{r exercise_3.1}
fisheries <- read_csv("data/fisheries.csv")
fisheries <- fisheries %>% filter(capture > 100000, total > 100000, aquaculture > 100000)
ggplot(data = fisheries,
       mapping = aes(x = capture, y = country))+
  geom_point()+
  labs(title = "Total Capture", subtitle = "by Country", x = "Tons Capture", y = "Country")
```

```{r exercise_3.2}
ggplot(data = fisheries,
       mapping = aes(x = aquaculture, y = country))+
  geom_point()+
  labs(title = "Total Aquaculture", subtitle = "by Country", x = "Tons Aquaculture", y = "Country")
```

```{r exercise_3.3}
ggplot(data = fisheries,
       mapping = aes(x = total, y = country))+
  geom_point()+
  labs(title = "Total Harvest", subtitle = "by Country", x = "Total Tons", y = "Country")
```

Add exercise headings as needed.
